language: cpp

os:
  - osx

compiler:
  - clang

install:
  - if [ "$TRAVIS_OS_NAME" = osx ]; then brew install glfw conan ccache; export PATH="/usr/local/opt/ccache/libexec:$PATH"; fi

script:
  - ./bootstrap.sh -y
  - ./build.sh

after_failure:
  - cat build/*/Testing/Temporary/LastTest.log

cache:
  ccache: true
