language: cpp
compiler: clang
os: osx
osx_image: xcode11

env:
  global:
    - MACOSX_DEPLOYMENT_TARGET=10.14
    - VK_SDK_VER=1.1.126.0

addons:
  homebrew:
    packages:
      - glfw
      - conan
      - ccache
      - ninja
      - doxygen

before_script:
  - |
    export VULKAN_SDK="$PWD/vulkansdk-macos-$VK_SDK_VER/macOS"
    if [ ! -d "$VULKAN_SDK" ]; then
      curl -O https://sdk.lunarg.com/sdk/download/$VK_SDK_VER/mac/vulkansdk-macos-$VK_SDK_VER.tar.gz
      tar xf vulkansdk-macos-$VK_SDK_VER.tar.gz && rm vulkansdk-macos-$VK_SDK_VER.tar.gz
    fi
  - ./bootstrap.sh -y
  - ./build.sh deps

script:
  - ./build.sh config build test install package

after_failure:
  - cat build/*/Testing/Temporary/LastTest.log

cache:
  ccache: true
  directories:
    - vulkansdk-macos-$VK_SDK_VER

before_deploy:
  - conan user -p $CONAN_PASSWORD -r xcikit rbrich
  - conan upload '*/*@rbrich/stable' --all --no-overwrite --check --confirm -r=xcikit

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: artifacts/*.zip
  on:
    repo: rbrich/xcikit
    branch: master
  skip_cleanup: true
  draft: true
