language: cpp
sudo: false
dist: trusty

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - libglfw3-dev
      - pegtl-dev

install:
  - if [ "$TRAVIS_OS_NAME" = osx ]; then brew install glfw pegtl; fi

script:
  - mkdir build && cd build
  - cmake ..
  - make
  - make test
