language: cpp

os:
  - osx

compiler:
  - clang

addons:
  homebrew:
    packages:
      - glfw
      - conan
      - ccache

script:
  - ./bootstrap.sh -y
  - ./build.sh

after_failure:
  - cat build/*/Testing/Temporary/LastTest.log

cache:
  ccache: true
