language: cpp

os:
  - osx

compiler:
  - clang

install:
  - if [ "$TRAVIS_OS_NAME" = osx ]; then brew install glfw conan; fi

script:
  - ./bootstrap.sh
  - ./conan/create-local.sh
  - mkdir build && cd build
  - conan install ..
  - cmake ..
  - cmake --build .
  - cmake --build . --target test
