language: cpp

os:
  - linux
  - osx

install:
  - if [ "$TRAVIS_OS_NAME" = linux ]; then sudo apt-get install libglfw3-dev pegtl-dev; fi
  - if [ "$TRAVIS_OS_NAME" = osx ]; then brew install glfw pegtl; fi

script:
  - mkdir build && cd build
  - cmake ..
  - make
  - make test
