language: cpp

os:
  - osx

compiler:
  - gcc
  - clang

install:
  - if [ "$TRAVIS_OS_NAME" = osx ]; then brew install glfw pegtl; fi
  - mkdir Catch; wget https://github.com/catchorg/Catch2/releases/download/v2.2.1/catch.hpp -O Catch/catch.hpp

script:
  - mkdir build && cd build
  - cmake -DCATCH_ROOT=$TRAVIS_BUILD_DIR/Catch ..
  - make
  - make test
