# CircleCI + Docker howto: https://circleci.com/docs/2.0/custom-images/

version: 2
jobs:
  build:
    docker:
      - image: rbrich/xcikit-debian:stretch

    steps:
      - checkout

      - run:
          name: Bootstrap
          command: |
            ./bootstrap.sh -y

      - run:
          name: Build
          command: |
            mkdir build && cd build
            conan install .. --build glad
            cmake .. -G Ninja
            cmake --build .

      - run:
          name: Run tests
          command: cmake --build build --target test
