# CircleCI + Docker howto: https://circleci.com/docs/2.0/custom-images/

version: 2
jobs:
  build:
    docker:
      - image: rbrich/xcikit-debian:buster

    steps:
      - checkout

      - run:
          name: Bootstrap
          command: ./bootstrap.sh -y

      - run:
          name: Deps
          command: ./build.sh -G Ninja deps

      - run:
          name: Configure
          command: ./build.sh -G Ninja config

      - run:
          name: Build
          command: ./build.sh -G Ninja build

      - run:
          name: Run tests
          command: ./build.sh -G Ninja test

      - run:
          name: Install
          command: ./build.sh -G Ninja install

      - run:
          name: Package
          command: ./build.sh -G Ninja package

      - store_artifacts:
          path: artifacts
