name: C/C++ CI
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: install tools
      run: pip3 --no-cache-dir install conan

    - name: bootstrap
      run: ./bootstrap.sh -y --no-shaders

    - name: deps
      run: ./build.sh deps
      
    - name: configure
      run: ./build.sh config -D XCI_WITH_VULKAN=0
      
    - name: build
      run: ./build.sh build
      
    - name: test
      run: ./build.sh test
      
    - name: install
      run: ./build.sh install
      
    - name: package
      run: ./build.sh package
